server:
  port: ${SERVER.PORT:8887}
  servlet:
    context-path: /web

spring:
  profiles:
    active: ${SPRING.PROFILES.ACTIVE:dev}
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

